apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lvxnut2xx-java-springboot 
  janus-idp.io/tekton: lvxnut2xx-java-springboot
  backstage.io/kubernetes-id: lvxnut2xx-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lvxnut2xx-java-springboot
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml